module.exports = [
  "an ancient pond",
  "with a sound from the water",
  "hear the frog as it plunges in",
  "just enough to bend",
  "the gladiolus leaves",
  "a cloud of flowers",
  "i come weary,",
  "in search of an inn",
  "ah! these wisteria flowers!",
  "the cry of the cicada",
  "it gives us no sign",
  "presently i will die",
  "the gate i would knock at",
  "the moon of today",
  "ah! the waving lespedeza",
  "it spills not a drop",
  "of the clear dew",
  "it was the new moon",
  "since then i waited",
  "and lo! tonight!",
  "i have my reward",
  "clouds will separate us",
  "the time to part has come now",
  "wild goose flies away",
  "the mysterious power of harmony",
  "freed from all my woes",
  "night, the city has calmed down",
  "behind the large window",
  "it is quiet and solemn",
  "as if a man dies",
  "distracted by failure,",
  "we look at the stars",
  "and again look at the stars",
  "stars, stars",
  "where does this melancholy come from?",
  "and stars speak",
  "stars tell everything",
  "time's river in its rushing current",
  "nations, kingdoms and their kings,",
  "is there something remaining?",
  "the sounds of lyre or the trumpet's air",
  "where have we come from? ",
  "where are we going?",
  "we can't comprehend.",
  "so many pure souls",
  "under the blue circle of sky",
  "burn into ashes! ",
  "but where is the smoke?",
  "what do you mean to the world?",
  "our existence is like smoke",
  "two abysses yawn from each sides",
  "you are in between",
  "the rose said: oh, my most radiant beauty",
  "one who has smiled for a moment",
  "the nightingale answered",
  "it's so hard to hear your voice",
  "in the autumn wind.",
  "soon i must to die,",
  "there is no sign of it",
  "the cicadas cry",
  "on a withered branch",
  "a crow is sitting",
  "this autumn eve",
  "listen well!",
  "lo!",
  "ho!",
  "the fallen flowers",
  "they return to their branch",
  "we become butterflies",
  "a worm digs silently",
  "a summer river being crossed",
  "how pleasing",
  "worlds in my hands",
  "stars in the sky",
  "the rolling of thunder",
  "daybreak's red knife in the sky",
  "creeping eastward",
  "moving west",
  "it seems far away, that thunder",
  "the scent of the wisteria",
  "i become nothing",
  "i leave as i entered",
  "o snail",
  "climb mount fuji",
  "but slowly, slowly!",
  "i bed farewell",
  "to the departing year",
  "trust the moth and the trail",
  "everything i touch",
  "with tenderness, alas",
  "pricks like bramble",
  "winds howl in rage",
  "no leaves to blow",
  "the winter creeps closer",
  "the leave searches for the ground",
  "swaying in the evening sun",
  "i pivot to face you",
  "a leafless tree",
  "a mind bare as a birch",
  "the crown has flown away",
  "shall we return, you and i?",
  "i walk alone",
  "you will never hear me leave",
  "a cool fall night",
  "the light staggers out of the day",
  "we fall like leaves",
  "not yet a butterfly",
  "a cicada shell",
  "a song that sings itself",
  "away and away and away",
  "night in the cemetery",
  "moonshadows from the tombs",
  "clouds hide the moon",
  "dew on the melons",
  "slain by time",
  "time, the destroyer!",
  "the trail breaks in two",
  "a monk sips his morning tea",
  "it's quiet",
  "the flowering of the crocus",
  "salmon arch through the air",
  "the woods are dark tonight",
  "trails in the morning snow",
  "awake, awake, all night",
  "the drip of a water clock",
  "can you understand?",
  "will you perceive this?",
  "will this fit inside your mind?",
  "the cracking of the winter ice",
  "the winter is over",
  "the winter has begun",
  "you feel the winter begin",
  "bitter this flavor on your tongue",
  "just enough to slake the thirst",
  "a rat scurries away",
  "a light even the moths cannot see",
  "a stone rolls for centuries",
  "the planets gaze silently",
  "your robe clings in the rain",
  "creeks warble like the thrush",
  "a splash, a ripple, then gone",
  "shall i say what i see?",
  "a trail that leads back here",
  "cold night, the ducks fly south",
  "the sky is sick",
  "it sleeps for a while",
  "waking in the night",
  "i saw my death approach, and withdrew",
  "unsheathing my sword",
  "i shook my fist at the clouds",
  "the stubble on the fields",
  "and then?",
  "and how?",
  "and why?",
  "and where?",
  "with who will you go?",
  "winter rain",
  "the cock crows",
  "newly washed by the spring",
  "ill on a journey you will not complete",
  "over a withered moor",
  "my dreams wander",
  "the horses fall silent",
  "flecked with mud",
  "have i been here before?",
  "i have been here before",
  "you have been here before",
  "don't imitate me",
  "your mind slows to a halt",
  "two halves of an orange",
  "cut precisely in half",
  "cut rudely in half",
  "first day of spring",
  "i keep thinking",
  "about autumn",
  "when will you come, death?",
  "had i known, i could have been brave",
  "the snail in its warrior shell",
  "first snow",
  "last rains",
  "before the night comes",
  "crossing a half-finished bridge",
  "even the chickens fall silent",
  "shall you take my coat?",
  "i offer you my hand",
  "you offer a hand",
  "see, i have found you out",
  "the fleas and lice",
  "a pillowful of dreams",
  "a hill without a name",
  "veiled in the morning mist",
  "so the end has come like this",
  "when i reach for it, my sword shatters",
  "my sword shatters on death",
  "death has no use for my weapons",
  "this door i cannot open",
  "this door i cannot shut",
  "the wind blows my last leaves away",
  "the last leaf falls from my brow",
  "i will die like a tree",
  "if i must die, die like a tree",
  "the husk breaks open, and i am within",
  "the first breath when i break the surface",
  "the surface of the water is still again",
  "a flash of lightning: what is it?",
  "death will soon knock on that door",
  "the dark sea at night ",
  "i float like a leaf on the raging sea",
  "i float until the end of the ocean",
  "the thunder prepares its voice",
  "heat waves shimmer on the road",
  "can you see?",
  "can you feel it?",
  "above the dying grass",
  "how admirable!",
  "to see lighting",
  "life is fleeting",
  "life is long",
  "in this world of ours",
  "we eat as if there is no tomorrow",
  "what comes next?",
  "the oceans rise to meet us",
  "at last, the last breath",
  "mid-field",
  "a stranger on the road: who are you?",
  "the skylark singing",
  "attached to nothing",
  "the door moves on its hinge",
  "clock stops, holds, starts",
  "these strange messengers",
  "the arrow arrives",
  "the final blow arrives",
  "at last, laughter",
  "ah!",
  "aha!",
  "nothing, and nothing",
  "a wandering path",
  "a wandering mind",
  "how shall i go?",
  "thunder splits the sky",
  "thunder splits my mind",
  "lightning splits the oak",
  "an oak split by time",
  "shhh. can you hear it?",
  "and shall we now dance?",
  "come, take my hand",
  "come, take death's hand",
  "the hooded figure arrives",
  "beckoning from across the stream",
  "step into the cold waters",
  "a first step into the snow",
  "the pond untroubled by time",
  "a final laugh, then silence",
  "and what should i regret?",
  "it was all an illusion",
  "the wind-shaken maples",
  "the cat watches, silent",
  "turning and turning",
  "oh, oh",
  "it cannot be",
  "i fall silent",
  "the moon hides in the forest",
  "the forest hides the moon",
  "long shadows on the snow",
  "your shadow grows long",
  "your shadow reaches the woods",
  "someone watches from the woods",
  "someone is watching",
  "waves of rain",
  "the rain washes it all away",
  "no!",
  "strike now, or never",
  "let the wind cry",
  "i remember your white gown",
  "the moon rises; i fall",
  "the key turns in the lock",
  "you will not remember me",
  "i will not be remembered",
  "i grow weary of foreign cities",
  "the murmuring cities",
  "what detains you?",
  "i seek and desire",
  "a sparrow returns from long travel",
  "soul of sorrow, why this weeping?",
  "it can never be mine",
  "master of knowledge",
  "i am of small understanding",
  "wisdom, you are fled",
  "my spirit, dried and broken",
  "listen!",
  "never!",
  "leave!",
  "harken to that voice",
  "death's chariot, yoked, arrives",
  "carried away by sparrows",
  "smiling and immortal",
  "suddenly near me",
  "over the dark earth",
  "soon shall i follow",
  "suddenly in your presence",
  "suddenly, a presence felt",
  "flush with fever",
  "shaking with my end days",
  "sailors make seaward",
  "seeking the skyline",
  "fabulous islands",
  "what undiscovered worlds!",
  "the sea's secret, still",
  "returning to the cradle, still old",
  "this glowing and craving soul",
  "the foaming seas",
  "my frail heart",
  "the bending yellow grain",
  "grain thrashing in a storm",
  "humpbacked with rain",
  "we will never know why",
  "why? we will never know",
  "quick water in a channel",
  "hang garlands on the tomb",
  "beneath the pale, pale moon",
  "mirth before death",
  "scrape the strings, and let them speak!",
  "become a speaking tomb",
  "all that morning scatters, night returns",
  "in the apple boughts, the coolness",
  "i await the fluttering footfall",
  "through the twilight",
  "sleep wanders",
  "sleep will not come",
  "the purple shadows",
  "tell me, tell me!",
  "i am all impatience",
  "wait and listen",
  "watch the stars",
  "appear in the quiet blue",
  "the night is half gone",
  "the watch is nearly unwound",
  "children are called from the games",
  "the game ends",
  "the quiet of dusk",
  "i lie alone",
  "who can stop death in his course?",
  "the piping of far-off music",
  "your head thrown backwards",
  "i am a torrent",
  "love shakes my soul",
  "death cries",
  "the crickets sing, and i am awake",
  "awake while the crickets sign",
  "a message! a messenger!",
  "i fall, to never rise",
  "i hear the summons",
  "the summons comes",
  "in the faint blue foothills",
  "never to be resisted",
  "it arrives at your door",
  "the breath among the grasses",
  "the canopy of night",
  "dawn with its golden sandals",
  "untying the knot",
  "an unopened present",
  "the eyes of strangers, suspicious",
  "what detains you?",
  "who detains you?",
  "i am detained",
  "i cannot leave, cannot arrive",
  "a fever burns",
  "but will you come?",
  "the wind comes walking",
  "coolness and darkness",
  "the moving grasses",
  "o heart",
  "o mind",
  "o life",
  "o end",
  "o sky",
  "o darkness",
  "o planets",
  "o stars",
  "o rose",
  "the sad and sea-going ships",
  "this infinite regret",
  "spent like an arrow, never to return",
  "the god of the green world",
  "soft, the hill-fog",
  "i wander through life",
  "at my lover's door",
  "like torn sea-kelp in the drift",
  "the great tides of the sea!",
  "far beyond return",
  "past the portals of night",
  "i will bring you pearls",
  "when i am home from travel",
  "the journey ends",
  "our journey ends",
  "the rose-marble entry",
  "the spray of the prow in the ocean",
  "the endless night",
  "wandering the corridors, alone",
  "hearing my own heart beat",
  "the heart stops",
  "death stops all clocks",
  "the broken universe",
  "in the distance, a dark blue ravine",
  "a sigh from the oceans",
  "the narrow roads of the town, at night",
  "let love be your sea-star!",
  "knock, and enter, and do not leave",
  "how soon will my lovely days be over",
  "the tall beech-trees",
  "the bright glance of dawn",
  "testament of tears",
  "destiny and disillusion",
  "the rainbow's end",
  "a rock thrown, a splash",
  "wise beyond all words",
  "when love leads to peril",
  "man and stars and sea",
  "the broken ocean",
  "it can never be mine",
  "it will never be yours",
  "to sit at the door and wait",
  "a pageant, and a dream",
  "will all things of the earth",
  "stop!",
  "halt!",
  "depart!",
  "begone!",
  "thou! and thou!",
  "the gods have given you nothing",
  "wise as you are",
  "foolish as you are",
  "strong as the spirit can be",
  "beyond the storm of tears",
  "doubt shakes like a wind",
  "shaken like a tree by wind",
  "in a strange land i wander",
  "there is nothing left to say",
  "on the threshold, a new planet",
  "softly the wind moves",
  "the wind-shaken leaves",
  "the west wind whips",
  "travel by the wind's road",
  "the grapes ungathered",
  "the lightning strikes",
  "the fire is kindled",
  "the last embers gone",
  "ask the wandering winds",
  "ha!",
  "no one knows",
  "the braying of brazen horns",
  "the crimson sinking sun",
  "a world born in a cradle",
  "this fragile heart",
  "i heard the gods reply",
  "blue smoke on the hill",
  "an empty room",
  "footsteps in the hall",
  "why do the gods not die?",
  "tell me what life means",
  "what should we do, but love?",
  "truth itself is heard",
  "the flawless player",
  "ashes cold and grey",
  "this fond imagining",
  "in the shadows of the gods",
  "solitude smiled",
  "so many hurrying home",
  "before it ends",
  "before it begins",
  "flutter, my timorous heart",
  "expectation and doubt",
  "dread mounts",
  "death mounts his steed",
  "my heart thrown like a stone",
  "how can i say this?",
  "spring returns",
  "filled with fire",
  "the spirit of fury",
  "o fury!",
  "o death!",
  "ah, sadness again",
  "the echo of birth",
  "a roof over the soul",
  "what treasures in its hold",
  "what secrets within",
  "loosening the tongue",
  "rose-petals strewn before you",
  "glad as a dream",
  "with its maddening smile",
  "the smile of madness",
  "the blue dome of dusk",
  "the burnt city",
  "soft was the wind in the beeches",
  "nothing but sea-sounds",
  "gone like the tide",
  "have you heard the news?",
  "have you heard?",
  "the herald arrives, like dawn",
  "sad and wayward beauty",
  "pure air that feeds a forge's hunger",
  "the hungering flames",
  "the bright stain of poppies",
  "love is so strong a thing",
  "a word, a look, can kill",
  "this desolation",
  "a last glance backwards",
  "hello, traveller",
  "goodbye, traveller",
  "now you are well and truly lost",
  "ah, the hyacinths!",
  "handfuls of rain",
  "over the hills, the thunder",
  "the armies approach",
  "sounding the summons",
  "the ache of a memory",
  "the moonpulled waves",
  "the air cut by arrows",
  "a three-army clash",
  "the fire burns and burns",
  "hope dried as a riverbed",
  "o my lost love",
  "where is all that wonder?",
  "glad am i of it",
  "i can almost hear your song",
  "why have the gods left?",
  "grabbed in anger's grip",
  "held fast by time's talons",
  "carried in time's beak",
  "like one enchanted",
  "a rock, a stone, a boulder",
  "an immovable stone",
  "a world hangs on a branch",
  "an unpicked hope, yet ripe",
  "then i knew you",
  "ah, then i knew you",
  "can you truly see?",
  "can you see it?",
  "there i saw you, again",
  "the passers-by look down",
  "unsullied, wild, and delicate",
  "unbroken as a dandelion in a storm",
  "no more foolish than children",
  "when the spring swallows return",
  "the swallows will never return",
  "the horses surge",
  "the armies surge",
  "cover the sun with your hand",
  "the racing billows plunge and bloom",
  "a snowflake melts on your shoulder",
  "the ice, unmelted",
  "this golden summer",
  "falling and surging",
  "ceaseless and eternal",
  "the quick and the dead",
  "older than zeus",
  "what daydream is this?",
  "and none remembers, none",
  "the mighty sea-sounds",
  "seafoam like horses",
  "poseidon pounds the sands",
  "the forge glows in the night",
  "the glass speaks",
  "trembling before me",
  "the hour at last",
  "at last it comes",
  "it comes! at last!",
  "a flurry in the heart",
  "hark!",
  "hark! on the threshold!",
  "folding like paper in skillful hands",
  "once more into the mountains",
  "once more into the rain",
  "what burden of sorrow",
  "a leaping frog",
  "nevermore to return",
  "nevermore to leave",
  "gone like all things mortal",
  "now the song is song",
  "now the song is over",
  "a purple-dark ravine",
  "a ravine deep as sorrow",
  "you are alone now",
  "i am alone now",
  "no!",
  "no!",
  "no!",
  "no!",
  "yes!",
  "yes!",
  "yes!",
  "the trees fractal against the sky",
  "the thunder mutters and retreats",
  "the leaves rustle, uncertain where to go",
  "the cold scrape of the whetstone",
  "do you see it now? do you see?",
  "i will never find it again",
  "you and i must leave, never to return",
  "i hold my hand out; take it!",
  "the thirsty earth beneath our feet",
  "the earth knows and will never say",
  "your eyes dim with confusion",
  "you cannot say! i cannot say!",
  "birch pale as bones in the moonlight",
  "too far, too near",
  "too far, too far",
  "i turn my back one last time",
  "even the dead are impressed",
  "a day with no ancestor",
  "a smile light and gaily given",
  "is this a mystery?",
  "and what of it?",
  "nothing, and nothing, and nothing",
  "it all ends today",
  "or will it?",
  "can you? can i?",
  "like a cry in the dark of night",
  "the hail clatters like coin",
  "the knife cold against your cheek",
  "the hunter halts, still as stone",
  "o midnight",
  "see! the moon follow us, too",
  "the wolves circling, silent",
  "can this be my end?",
  "can this be your end?",
  "had I only but known",
  "youth is flown",
  "youth flies",
  "icicles hang in the trees",
  "worlds away",
  "aha!",
  "aha!",
  "the river shivers",
  "shh, shh, says the river",
  "we rise to leave",
  "we rise to leave at last",
  "the snow's rosepetal kiss",
  "the ashes of the town",
  "the ashes of my heart",
  "a light far off in the forest",
  "the forest mutters at night",
  "what news?",
  "news from my childhood town",
  "a dented shield",
  "your spear breaks at midnight",
  "the fir trees hoary with frost",
  "the moan of the wind on the lake",
  "o return!",
  "o end!",
  "a sparrow alights on your spear",
  "a cat moves silently away",
  "we walk without speech",
  "how the bronze dazzles in daylight",
  "thundering poseidon",
  "hear the earth-shaker!",
  "the rattle of an empty gourd",
  "no my friend, it is done",
  "you take my hand, and i yours",
  "lighting splits the stump",
  "silent as lightning above clouds",
  "the town deserted. where have they gone?",
  "the town empty at dusk",
  "swept up in war's embrace",
  "the coals cold now and silent",
  "i kneel, awaiting the blow",
  "a walking stick cast aside",
  "the path worn through grass",
  "daybreak!",
  "come sit with me awhile",
  "sparks from the struck steel",
  "a flint, a blow, the fire",
  "the scratch of a match. light!",
  "all frozen but the running stream",
  "the sound of footsteps following",
  "a growl in the woods",
  "the burning walls of troy",
  "yes, yes, and yes",
  "nothing but echos",
  "a creak at the gate. o visitor!",
  "a figure in the door",
  "you have returned",
  "mars rages in your heart",
  "so silently they hunt",
  "o moon",
  "o swallows",
  "a single drop of blood",
  "silver clouds of breath",
  "the still-warm coals of battle",
  "a cracking of the ice",
  "i cast all weapons aside",
  "the bells ring in a faroff temple",
  "i walked until i fell",
  "warm beneath blankets of snow",
  "a secret!",
  "no secrets",
  "the sky an open palm",
  "the armies depart",
  "clouds touch the mountain",
  "a young god, laughing",
  "the unbroken face of the pond",
  "like one who fights with the sea",
  "like one who brawls with the wind",
  "like one who battles the sky",
  "a star cuts the sky",
  "the call to arms",
  "a sudden peace",
  "a rose against the snow",
  "the owl at dusk in his tree",
  "the cold laugh of the brook",
  "here we will rest",
  "here we will stop",
  "the harness tight in your grasp",
  "the ice breaks, and, beneath!",
  "the lazy fruit hangs low",
  "unfinished business, you and i",
  "we walk in silence",
  "the stars whisper",
  "the willow bows to the brook",
  "the sound of distant footsteps",
  "a key turns in the lock",
  "dark steel of moonshadows",
  "o moon",
  "laughter from the darkness",
  "a bird in a young tree",
  "I become an arrow",
  "and what shall you do now?",
  "the click of the lock",
  "cold steel in the night",
  "the pigeons scatter, return",
  "the tomb empty in moonlight",
  "the sad laughter of crows",
  "the drums of war",
  "the last petal falls away",
  "you are here, i am not",
  "you stand at my tomb",
  "tomb shadows in the moonlight",
  "three trees charred by fire",
  "it will return when you least expect",
  "it will never return",
  "ash rising from the fire's heat",
  "a single word scrawled in the sand",
  "someone follows",
  "it seems we are not alone",
  "breath held like the blue sky",
  "starfire above the ruins",
  "the loon's cry across the bay",
  "a dagger frozen in ice",
  "take aim and do not miss",
  "strike now or strike never",
  "alone on a windswept hill",
  "you have forgotten, have you?",
  "you never knew, did you?",
  "you knew this once",
  "these tracks were left by you",
  "the bells begin to toll",
  "a skin of wine long dry",
  "fire devours the hills",
  "no one will come here again",
  "your journey cannot end",
  "steel dulled by time",
  "the drip of a water clock",
  "a tree alive with birdsong",
  "the willow bows to the pond",
  "the moon hides",
  "o song",
  "o thrush",
  "here we will rest",
  "the crimson skies of dawn",
  "bronze blazes as the fire nears",
  "an arrow broken in half",
  "you come across cold coals",
  "a dry laugh",
  "i have seen your face before",
  "who walks behind us?",
  "and it ends",
  "and it begins",
  "o hills",
  "o stones",
  "these stones, these hills, this water",
  "the crack of a burning log",
  "lightning, cloud to cloud",
  "impossible!",
  "impossible!",
  "it cannot be",
  "blown off course again",
  "sails hang in the motionless air",
  "three weeks at sea",
  "the gods laugh",
  "the gods will ignore you",
  "the gods have left",
  "the gift of sleep",
  "untie this knot",
  "the hungry wolves follow",
  "even the gods grow tired",
  "the laughter of the fountain",
  "like one who fells a tree",
  "like one who walks in silence",
  "the scrape of a violin's strings",
  "nothing, and nothing",
  "a white rose amongst the coals",
  "i will not return, nor will you",
  "you shake my hand at last",
  "i offer you my sword",
  "kneeling before the blow",
  "a cry. an echo!",
  "have they all gone? will they return?",
  "ride through the empty city",
  "a brightening glance",
  "the waterwheel spins",
  "i see you now",
  "you will never see it",
  "the name you cannot speak",
  "a name the world forgot",
  "a song that never ends",
  "a bee inspects the flower",
  "i will no longer study war",
  "a war that begets itself",
  "a hare flees into the grass",
  "how sweet, the grass-scent",
  "o grasses!",
  "o tomb",
  "cradling my heart like an infant",
  "i am done with our war",
  "i am done with this war",
  "i am done with my war",
  "i misremembered",
  "gone like wisps of memory",
  "heavy as a stone",
  "no words come",
  "will you stay?",
  "stay awhile with me",
  "the hiss of rain on the embers",
  "a snake in our path",
  "a frog suns on the warm stones",
  "o snake",
  "aha!",
  "beneath the roads, the dead",
  "beneath the city, the dead",
  "an echo in the tomb",
  "i turn slowly to face you",
  "observe the hawk as it hunts",
  "for what do you hunt in vain?",
  "what are you looking for, in the dark?",
  "cold iron of a locked gate",
  "plant your sword in the ground",
  "lower your weapon, i am a friend",
  "lower your sword, i am no thread",
  "the last breath before diving",
  "a cold whistle at midnight",
  "the cock crows in a distant field",
  "you will never discover it",
  "it will never be yours",
  "we should turn back now",
  "the groan of a dam yet to burst",
  "the raven cocks its head and observes",
  "athena's cold gaze",
  "the mockery of the gods",
  "what you thought treasure is dirt",
  "the iron shadows of the moon",
  "your sword strikes the earth",
  "sword-steel, pale in the moonlight",
  "inside the gourd, the worm",
  "awake all night, to greet the dawn",
  "three fires to please the gods",
  "my soul empty as a pocket",
  "aha! your fortune tilts like a table",
  "the crows all in a circle now",
  "you offer your words like gifts",
  "a present tied with a bow",
  "untie this knot, and free what is within",
  "dazzled by chrysanthemum",
  "cool beneath the sunflowers",
  "the silence of the knives",
  "the sky peers up from inside the pond",
  "silence!",
  "we should both be quiet now, you and i",
  "the temple bells silenced with cotton",
  "my mind a sword undrawn",
  "a curtain of mist",
  "an army of daisies",
  "a rose, shy amongst thorns",
  "take my hand",
  "a wandering path",
  "trees touch the clouds",
  "cicadas cry in the lonely trees",
  "our spring is nearly done",
  "held in the hot grasp of fury",
  "sweet smell of the over-ripe pears",
  "a promise empty as a bowl",
  "deep in the forest, a searchlight",
  "that knife you hold was once mine",
  "the tap of a cane at the door",
  "three armies climb the mountain",
  "a wind plays with my candle",
  "you did not recognize me, did you?",
  "a weight even the gods cannot bear",
  "a castle against the moon",
  "the years climb like ivy",
  "i left my broken house behind",
  "the grain of sand that seeds a pearl",
  "lower your sword; i am, i think, a friend",
  "the frozen heart of the mountain",
  "the mouth of an empty mine",
  "what lives beneath the snow?",
  "two enemies at the table",
  "a rook, a knight, a pawn",
  "no longer a game; we begin",
  "a flag waves goodbye",
  "hello, old friend",
  "the bare sun stuns",
  "the trees throw down their leaves",
  "thrashing like oak in a storm",
  "cold, cold, and cold",
  "the snow is still falling",
  "no leaves left to fall",
  "take my hand",
  "i give up my sword",
  "no need now for weapons",
  "the battle turns",
  "begin!",
  "impossible",
  "o furies",
  "the end!",
  "immense",
  "a drip -- a single drop",
];
